/*
EVENTS 

events are actions or occurences that happen in the browser often triggered by user interactions (like clicks, keypresses, or form submissions).

syntax
with single quotes
<element event = 'some javascript code'>

with double quotes
<element event = "some javascript code">

event description
onchange - An HTML element has been changed
onclick - the user clicks an HTML element
onmouseover - the user moves the mouse over an HTML element
onmouseout - the user moves the mouse away from an HTML element
onkeydown - the user pushes a keyboard key
onload - the browser has finished loading the page
*/

function displayDate() {
  document.getElementById("demo1").innerHTML = Date();
}

/* 
EVENT LISTNER
the most appropriate way to write codes relating to events is by using the addEventListener() method. this method attaches an event handler to the specified element without overwriting existing event handlers.*/

const btn = document.getElementById("myBtn");
btn.addEventListener("click", function () {
  document.getElementById("demo2").innerHTML = Date();
});

/*

class work

1. create a html button and a well styled div. whene the button is clicked, the inner html of the div should change to "Javascript" is the best programming language

*/
const clBtn = document.getElementById("JSBtn");

clBtn.addEventListener("click", function () {
  document.getElementById("tag").innerHTML =
    "Javascript is the best programming language";
});

/* MOUSE EVENT 
mouse event happens when the user interacts with a mouse. some of the mouse events include:
click - when the user clicks an element
dblclick - when the user double clicks an element
mouseover - when the user moves the mouse over an element
mouseout - when the user moves the mouse away from an element
mousemove - when the user moves the mouse while it is over an element


*/

// mouseover and mouseout

const box = document.getElementById("box");

box.addEventListener("mouseover", function () {
  box.innerHTML = "Mouse is over me";
});

box.addEventListener("mouseout", function () {
  box.style.backgroundColor = "navy";
  box.style.color = "white";
  box.style.padding = "20px";
  box.innerHTML = "Mouse is out of me";
});

// mouse-double-click
const myButton = document.getElementById("myBTN");
const message = document.getElementById("message");

myButton.addEventListener("dblclick", function () {
  message.textContent = "Button was double clicked";
});

myButton.style.backgroundColor = "green";
setTimeout(() => {
  myButton.style.background = "";
}, 2000);

// mouse move
const tracker = document.getElementById("tracker");
const coords = document.getElementById("coordinates");

tracker.addEventListener("mousemove", function (e) {
  coords.textContent = `X: ${e.clientX}, Y: ${e.clientY}`;
});

// mouse up and down
const pressArea = document.getElementById("pressArea");
const statusText = document.getElementById("status");

pressArea.addEventListener("mousedown", function () {
  statusText.textContent = "Mouse Status: Down";
  pressArea.style.backgroundColor = "blue";
});

pressArea.addEventListener("mouseup", function () {
  statusText.textContent = "Mouse status: up";
  pressArea.style.backgroundColor = "yellow";
});

// mouse enter and leave

const hoverBox = document.getElementById("hoverBox");
const hoverStatus = document.getElementById("hoverStatus");

hoverBox.addEventListener("mouseenter", function () {
  hoverStatus.textContent = "Inside the Box";
  hoverBox.style.backgroundColor = "navy";
  hoverBox.style.padding = "20px";
  hoverBox.style.fontSize = "20px";
  hoverBox.style.color = "white";
});

hoverBox.addEventListener("mouseleave", function () {
  hoverStatus.textContent = "Outside the Box";
  hoverBox.style.backgroundColor = "red";
});

// context menu event
const rightClickArea = document.getElementById("rightClickArea");

rightClickArea.addEventListener("contextmenu", function (e) {
  e.preventDefault();
  alert("custom right-click menu would open here");
});

// keyboard events
const keyz = document.getElementById("k");

keyz.addEventListener("keydown", function (event) {
  document.getElementById("demi").innerHTML = "you pressed: " + event.key;
});

/*
timing events 

timing is driven by timing events generated by the system clock. 
timing events are used to schedule code execution at specified time intervals


common timing events:
1. SetTimeOut (function, milliseconds) - executes a function once after a specified number of milliseconds.
2. setInterval(function, milliseconds) - repeatedly executes a function at specified time intervals (in milliseconds) until stopped.
3. clearTimeout (timeoutID) - stops a function that was to execute with setTimeout().
4. clearInterval (intervalID) - stops a function that was set to excute repeatedly with setInterval().
*/

setInterval(showTime, 1000);

function showTime() {
  const d = new Date();
  document.getElementById("clock").innerHTML =
    d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds();
}

// settimeout

const btntime = document.getElementById("btnTime");

btntime.addEventListener("click", function () {
  setTimeout(showMsg, 3000);
});

function showMsg() {
  document.getElementById("demor").innerHTML = "i waited 3 second";
}

// setinterval 2

let myInterval;
let count = 0;

const btnStart = document.getElementById("start");
const btnStop = document.getElementById("stop");

// add event listner to start button

btn.start.addEventListener("click", function () {
  myInterval = setInterval(Counter, 1000);
});

// add eventlistener to stop button

btnStop.addEventListener("click", function () {
  clearInterval(myInterval);
});

// declare the counter function
function counter() {
  count++;
  document.getElementById("counter").innerHTML = count;
}
